---
# tasks file for f5-azure-scca-external-setup
- name: Provision modules
  bigip_provision:
    server: "{{item.server}}"    
    user: "{{f5_username}}"
    password: "{{f5_password}}"
    module: "{{item.module}}"
    level: "{{item.level}}"
  with_items:
     "{{setup.modules}}"

- name: Add iApp
  bigip_iapp_template:
    content: "{{ lookup('file','f5.cloud_logger.v1.0.0.tmpl') }}"
    server: "{{item.server}}"    
    user: "{{f5_username}}"
    password: "{{f5_password}}"
    state: present
  with_items:
    "{{setup.oms}}"

- name: Add iApp Service
  bigip_iapp_service:
    name: "OMS"
    template: "f5.cloud_logger.v1.0.0"
    parameters: "{{ lookup('template','f5.cloud_logger.params.json') }}"
    server: "{{item.server}}"    
    user: "{{f5_username}}"
    password: "{{f5_password}}"
    state: present
  with_items:
    "{{setup.oms}}"


- name: Add Routes
  bigip_static_route:
    destination: "{{item.destination}}"
    gateway_address: "{{item.gateway_address}}"
    name: "{{item.name}}"
    server: "{{item.server}}"
    user: "{{f5_username}}"
    password: "{{f5_password}}"
  with_items:
     "{{setup.routes}}"

- name: Add iRules
  bigip_irule:
      content: "{{item.content}}"
      module: "ltm"
      name: "{{item.name}}"
      password: "{{f5_password}}"
      server: "{{item.server}}"
      state: "present"
      user: "{{f5_username}}"
  delegate_to: localhost
  with_items:
     "{{setup.irules}}"

- name: Add Pools
  bigip_pool:
    name: "{{item.name}}"
    server: "{{item.server}}"
    user: "{{f5_username}}"
    password: "{{f5_password}}"
  with_items:
     "{{setup.pools}}"

- name: Add Pool Members
  bigip_pool_member:
    name: "{{item.name}}"
    server: "{{item.server}}"
    user: "{{f5_username}}"
    password: "{{f5_password}}"
    pool: "{{item.pool}}"
    host: "{{item.host}}"
    port: "{{item.port}}"
    name: "{{item.name}}"
  with_items:
     "{{setup.pool_members}}"

- name: Check commands
  bigip_command:
    server: "{{item.server}}"
    user: "{{f5_username}}"
    password: "{{f5_password}}"
    commands:
       - "{{item.check}}"
  with_items:
    "{{setup.commands}}"
  register: result
- name: Run commands
  bigip_command:
    server: "{{item.item.server}}"
    user: "{{f5_username}}"
    password: "{{f5_password}}"
    commands:
      - "{{item.item.command}}"
  with_items:
    "{{result.results}}"
  when: 
    - '"was not found" in item.stdout|first'


- name: Check virtuals
  bigip_command:
    server: "{{item.server}}"
    user: "{{f5_username}}"
    password: "{{f5_password}}"
    commands:
      - tmsh show ltm virtual {{item.name}}
  with_items:
    "{{setup.virtuals}}"
  register: result

- name: Create Virtuals
  bigip_command:
    server: "{{item.item.server}}"
    user: "{{f5_username}}"
    password: "{{f5_password}}"
    commands:
      - tmsh {{item.item.command}}
  with_items:
    "{{result.results}}"
  when: 
    - '"was not found" in item.stdout|first'

- name: Check Route tags f5_ha
  command: az network route-table show --resource-group "{{item.resource_group}}" --name "{{item.name}}" --query tags.f5_ha
  with_items:
    "{{setup.route_tables}}"
  register: result

- name: Update Route tags f5_ha
  command: az network route-table update --resource-group "{{item.item.resource_group}}" --name "{{item.item.name}}" --set tags.f5_ha={{item.item.f5_ha}}
  with_items:
    "{{result.results}}"
  when: 
    - 'item.item.f5_ha != item.stdout[1:-1]'

- name: Check Route tags f5_tg
  command: az network route-table show --resource-group "{{item.resource_group}}" --name "{{item.name}}" --query tags.f5_tg
  with_items:
    "{{setup.route_tables}}"
  register: result

- name: Update Route tags f5_tg
  command: az network route-table update --resource-group "{{item.item.resource_group}}" --name "{{item.item.name}}" --set tags.f5_tg={{item.item.f5_tg}}
  with_items:
    "{{result.results}}"
  when: 
    - 'item.item.f5_tg != item.stdout[1:-1]'
