#cloud-config

write_files:
  - path: /etc/rsyslog.d/10-rsyslog.conf
    content: |
      *.*   @${log_destination}:514
  - path: /etc/networkd-dispatcher/routable.d/10-ifup-hooks
    content: |
      #!/bin/sh
      # ifconfig $IFACE 0.0.0.0 up
      # ip link set $IFACE promisc on
      sudo iptables -I FORWARD -i eth1 -o eth2 -j NFQUEUE --queue-num=4
      sudo iptables -I FORWARD -i eth2 -o eth1 -j NFQUEUE --queue-num=4
      exit 0
  - path: /etc/networkd-dispatcher/routable.d/50-postup-hooks
    content: |
      #!/bin/sh
      if [ $IFACE != "eth0"]
      ethtool -K $IFACE gro off lro off
      fi
      exit 0
  - path: /etc/networkd-dispatcher/dormant.d/promisc_bridge
    content: |
      #!/bin/sh
      set -e
      if [ $IFACE != "eth0"]
      ip link set eth1 up promisc on
      ip link set eth2 up promisc on
      fi
      exit 0
  - path: /etc/networkd-dispatcher/off.d/50-ifdown-hooks
    content: |
      #!/bin/sh
      ip link set $IFACE promisc off
      ifconfig $IFACE down
      exit 0
  - path: /lib/systemd/system/snort.service
    content: |
      [Unit]
      Description=Snort NIDS Daemon
      After=syslog.target network.target
      [Service]
      Type=simple
      ExecStart=/usr/sbin/snort -D -c /etc/snort/snort.conf -Q
      [Install]
      WantedBy=multi-user.target

apt:
  primary:
    - arches: [default]
      search_dns: True
package_upgrade: true
packages:
  - build-essential
  - bridge-utils
  - libpcap-dev
  - libpcre3-dev
  - libdumbnet-dev
  - bison
  - flex
  - zlib1g-dev
  - liblzma-dev
  - openssl
  - libssl-dev
  - ethtool
  - autoconf
  - libtool
  - libtool-bin
  - pkg-config
  - gcc
  - zlib1g-dev
  - libluajit-5.1-dev
  - libnghttp2-dev
  - libdnet
  - git
  - libcrypt-ssleay-perl
  - liblwp-useragent-determined-perl
  - libnetfilter-queue-dev

runcmd:
  - sudo chmod +x /etc/networkd-dispatcher/routable.d/10-ifup-hooks
  - sudo chmod +x /etc/networkd-dispatcher/routable.d/50-postup-hooks
  - sudo chmod +x /etc/networkd-dispatcher/dormant.d/promisc_bridge
  - sudo chmod +x /etc/networkd-dispatcher/off.d/50-ifdown-hooks
  - sudo echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
  - sudo apt autoremove -y
  - sudo mkdir -p /etc/snort/rules
  - sudo chmod -R 5775 /etc/snort
  - sudo mkdir /var/log/snort
  - sudo chmod -R 5775 /var/log/snort
  - sudo mkdir -p /home/root/snort_src
  - cd /home/root/snort_src
  - [wget, "https://www.snort.org/downloads/snort/daq-2.0.7.tar.gz"]
  - [wget, "https://www.snort.org/downloads/snort/snort-2.9.16.1.tar.gz"]
  - [wget, "https://www.snort.org/downloads/community/community-rules.tar.gz"]
  - git clone https://github.com/John-Lin/docker-snort.git
  - tar -xvzf daq-2.0.7.tar.gz
  - tar -xvzf snort-2.9.16.1.tar.gz
  - tar -xvzf community-rules.tar.gz
  - cd /home/root/snort_src/daq-2.0.7
  - autoreconf -f -i
  - ./configure
  - make
  - sudo make install
  - cd /home/root/snort_src/snort-2.9.16.1
  - autoreconf -f -i
  - ./configure --enable-sourcefire
  - make
  - sudo make install
  - sudo ldconfig
  - sudo ln -s /usr/local/bin/snort /usr/sbin/snort
  - sudo mkdir -p /usr/local/lib/snort_dynamicrules
  - sudo cp /home/root/snort_src/snort-2.9.16.1/etc/* /etc/snort/
  - sudo touch /etc/snort/rules/white_list.rules /etc/snort/rules/black_list.rules
  - sudo cp /home/root/snort_src/docker-snort/snortrules-snapshot-2972/rules/* /etc/snort/rules
  - sudo echo "config policy_mode:inline" >> /etc/snort/snort.conf
  - sudo sed -i 's/..\/rules/\/etc\/snort\/rules/g' /etc/snort/snort.conf
  - "sudo sed -i 's/# config daq: <type>/config daq: nfq/g' /etc/snort/snort.conf"
  - "sudo sed -i 's/# config daq_mode: <mode>/config daq_mode: inline/g' /etc/snort/snort.conf"
  - "sudo sed -i 's/# config daq_var: <var>/config daq_var: queue=4/g' /etc/snort/snort.conf"
  - sudo echo 'alert icmp any any -> $HOME_NET any (msg:"ICMP test detected"; GID:1; sid:10000001; rev:001; classtype:icmp-event;)' >> /home/root/local.rules
  - sudo rm -rf /etc/snort/rules/local.rules
  - sudo cp /home/root/local.rules /etc/snort/rules/local.rules
  - sudo sysctl -p
  - sudo route add -net ${wafSubnetPrefix} netmask ${internalMask} gw ${wafGateway}
  - sudo route add -net ${internalSubnetPrefix} netmask ${wafMask} gw ${internalGateway}
  - sudo iptables -I FORWARD -i eth1 -o eth2 -j NFQUEUE --queue-num=4
  - sudo iptables -I FORWARD -i eth2 -o eth1 -j NFQUEUE --queue-num=4
  - sudo systemctl enable snort
  - sudo systemctl start snort
  #- sudo snort -D -c /etc/snort/snort.conf -Q

final_message: "The system is finally up, after $UPTIME seconds"
